### ISSUE TITLE
Harmony raise a exception when try run without datasource loaded on Druid

### ISSUE THREAD

**Issue by smithjunior** [Zenysis/Harmony#14]
Hello Guys,

Other problem I believe that I found in your code, when try to run Harmony without datasources loaded on Druid, the software crash because the your code raise a exception on 112 line inside the ./db/druid/metadata.py

```python
    # Return the most recent datasource for a given site
    def get_most_recent_datasource(self, site):
        LOG.info('Getting most recent Druid datasources...')
        output = None
        for ds in self.get_site_datasources():
            if ds.site == site and (not output or ds.date > output.date):
                output = ds
        if not output:
            raise MissingDatasourceException(
                'No datasource could be found matching site prefix: %s' % site
            )
        LOG.info('Got most recent Druid datasources')
        return output
```

```bash
20201110.134851.387 DEBUG settings.py:_populate_configuration_table:230: Configuration for 'public_access' did not exist in database, adding it.
20201110.134851.389 DEBUG settings.py:_populate_configuration_table:236: Added configuration entry for 'public_access'.
20201110.134851.390 DEBUG settings.py:_populate_configuration_table:230: Configuration for 'project_manager_ids' did not exist in database, adding it.
20201110.134851.392 DEBUG settings.py:_populate_configuration_table:236: Added configuration entry for 'project_manager_ids'.
20201110.134851.393 DEBUG settings.py:_populate_configuration_table:230: Configuration for 'crisp_id' did not exist in database, adding it.
20201110.134851.395 DEBUG settings.py:_populate_configuration_table:236: Added configuration entry for 'crisp_id'.
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
20201110.134851.508 INFO 24:MainThread: Context impl PostgresqlImpl.
20201110.134851.508 INFO 24:MainThread: Will assume transactional DDL.
20201110.134851.511 INFO app.py:_fail_if_schema_upgrade_needed:268: Database schema version is: 213b541d942f
20201110.134851.521 DEBUG settings.py:get_configuration:151: Retrieved value for key 'cur_datasource' was 'LATEST_DATASOURCE'
20201110.134851.601 INFO metadata.py:get_most_recent_datasource:106: Getting most recent Druid datasources...
Traceback (most recent call last):
  File "web/gunicorn_server.py", line 169, in <module>
    sys.exit(main())
  File "web/gunicorn_server.py", line 163, in main
    flask_application = create_app()
  File "/zenysis/web/server/app.py", line 466, in create_app
    db, flask_configuration, instance_configuration, configuration_module
  File "/zenysis/web/server/app.py", line 241, in _create_app_internal
    _initialize_druid_context(app)
  File "/zenysis/web/server/app.py", line 309, in _initialize_druid_context
    datasource = druid_metadata.get_most_recent_datasource(deployment_name)
  File "/zenysis/db/druid/metadata.py", line 113, in get_most_recent_datasource
    'No datasource could be found matching site prefix: %s' % site
db.druid.errors.MissingDatasourceException: No datasource could be found matching site prefix: br
```

I suggest a deal to allow the application to go up without datasources, your application should launch a WARNING,  but do not crash the application.

it is as like on a Crud screen it breaks because there is no data in a database table, do you know?

I hope I helped with this report.

**Comment by Sybrand** [comment]
@smithjunior thank you for reporting this, however all of Harmony's features are dependant on an existing data source so this exception is the expected behaviour.

I agree that is may not appear at first to be a very good user experience, but a) this should never happen in a production environment - and b) any kind of 500 error can be handled at the ingress point to provide an appropriate "site is down error".
